### ISSUE TITLE
Can Any one tell me even after tld set to com why it's connecting to translate.google.en?

### ISSUE THREAD

**Issue by RajrupDasid** [pndurette/gTTS#382]
I am using gTTS 2.3.0 latest
My parameters are set as

tts = gTTS(res,slow=False,lang="en",tld="com")

then why it's giving me error like below?

gtts.tts.gTTSError: Failed to connect. Probable cause: Host 'https://translate.google.en/' is not reachable

when this issue is going to remove?

**Comment by PanderMusubi** [comment]
Same for `gtts-cli -l es -t es ...` which results in

    Error: Failed to connect. Probable cause: Host 'https://translate.google.es/' is not reachable

**Comment by PanderMusubi** [comment]
Is there any progress on this issue as part of the functionality is broken at the moment?

**Comment by pndurette** [comment]
Hi @RajrupDasid & @PanderMusubi, I'm taking a look, this is odd, let me dig.

**Comment by pndurette** [comment]
@PanderMusubi Do you still get this error? I can't replicate at the moment.
Getting `Host xyz is not reachable` happens inside the `gTTSError` exception, when trying to come up with a meaningful error message. But the root cause is that the API request failed (which could be many reasons, the most probably one being that the host isn't reachable)

> Same for `gtts-cli -l es -t es ...` which results in
> 
> ```
> Error: Failed to connect. Probable cause: Host 'https://translate.google.es/' is not reachable
> ```

**Comment by pndurette** [comment]
@RajrupDasid: Sorry I'm late on this, but can you confirm this happens exactly with the code you provided? I can replicate, but also, I've been going though the code and I can't find any possible way that you would get this error message unless you used a `tld` set to `en`.

> I am using gTTS 2.3.0 latest My parameters are set as
> 
> tts = gTTS(res,slow=False,lang="en",tld="com")
> 
> then why it's giving me error like below?
> 
> gtts.tts.gTTSError: Failed to connect. Probable cause: Host 'https://translate.google.en/' is not reachable
> 
> when this issue is going to remove?

**Comment by PanderMusubi** [comment]
Meanwhile the error on the side of Google that was there for a few months has been fixed. It was broken for a while. Tetst script, that also illustrates the US/UK English from https://github.com/pndurette/gTTS/issues/313 is

    from gtts import gTTS
    tts = gTTS('Hello, good morning.', lang='en')
    tts.save('gtts-en.mp3')
    tts = gTTS('Hello, good morning.', lang='en', tld='co.uk')
    tts.save('gtts-en-couk.mp3')
    tts = gTTS('Hello, good morning.', lang='en', tld='us')
    tts.save('gtts-en-us.mp3')
    tts = gTTS('Hola, buenos días.', lang='es', tld='es')
    tts.save('gtts-es-es.mp3')

Please confirm and this issue can be closed.

**Comment by RajrupDasid** [comment]
@pndurette Check out this repository
[Project link](https://gitlab.com/open-source-projects-lambda/basicvoicechat/-/blob/master/main.py)
it's the code where i was getting the error no matter what i have done.

**Comment by RajrupDasid** [comment]
@PanderMusubi and @pndurette I am still facing the issues with up to dated modules.

**Comment by RajrupDasid** [comment]
@pndurette please click [Detailed Error Link](https://github.com/RajrupDasid/python_basic_voice/issues/1l)
to view yourself the full error
and if you want to see the code i have already pasted the repo link

**Comment by PanderMusubi** [comment]
@RajrupDasid from pip(3) or apt(-get). The latter is too old.

**Comment by PanderMusubi** [comment]
I have updated the test above with .com and that works file too with gtts 2.3.0

**Comment by pndurette** [comment]
@RajrupDasid—

As I suspected, this code isn't what yielded your error:

> tts = gTTS(res,slow=False,lang="en",tld="com")
> 
> then why it's giving me error like below?
> 
> gtts.tts.gTTSError: Failed to connect. Probable cause: Host 'https://translate.google.en/' is not reachable

Looking at the [code you sent me](https://github.com/RajrupDasid/python_basic_voice/blob/6f91939e03e630da8616ed9b10b5e745dfe54e1d/main.py#L84), I see the issue: the 2nd attribute is the `tld` and not `lang`. You can go around this by using named attributes:

```diff
- tts = gTTS(fst,'en')
+ tts = gTTS(fst, lang='en')
```

Just tested and it works.
